spring:
  application:
    name: eureka-server
  redis:
    host: 1.117.158.80
    port: 6379
    password: jiaxu123123
server:
  port: 8761

eureka:
  instance:
    hostname: eureka-server
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    peer-node-read-timeout-ms: 1000